name: "OpenAI Code Analyzer"
description: "OpenAI-based Code Analysis Library"
author: fukumone
branding:
  icon: check-square
  color: green
inputs:
  openai-api-key:  # id of input
    description: 'Your openai api key'
    required: true
  github-token:
    description: "Github token"
    required: true
  model:
    description: 'The model to use'
    required: false
    default: 'text-davinci-003'
runs:
  using: 'node16'
  main: 'dist/index.js'
